### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by szikszail** [judit-nahaj/gherkin-precompiler#14]
Add a command line interface which could precompile source feature files based on a configuration and write them to a destination.

The options which the CLI should accept:
- `--source, -s` - the path of any feature file or a glob expression; if not set, default: `{baseDirectory}/**/*.feature`
- `--base, -b` - the base directory of feature files; if not set, it is calculated from the `source`
- `--destination, -d` - the destination directory, where the feature files should be written; if not set, it will be the `{baseDirectory}/dist`
- `--config, -c` - the path of the JSON configuration file, default: `./precompiler.json`

`source` and `base` must be set either by command line options of in the configuration!

The format of the configuration should be the following:
```javascript
{
  "source": "...", // same as --source
  "base": "...", // same as --base
  "destination": "...", // same as --destination 
  "compilers": [
    // Array of pre-compiler configurations (see next)
  ]
}
```

The format of the precompiler configuration should be the following:
```javascript
{
  "type": "Replacer", // name of the precompiler class
  "arguments", [
    // Array of values which would have been passed to the precompiler itself
  ]
}
```

**Comment by szikszail** [comment]
@judit-nahaj could you please share your thoughts about this proposal?

**Comment by judit-nahaj** [comment]
@szikszail it seems useful, good idea. Would the option to name the output file be useful? Or what would be the name of the  precompiled output?

**Comment by szikszail** [comment]
@judit-nahaj all file would keep their original name.

E.g. the following command
```bash
gherkin-precompiler --source e2e/features/src/**/*.feature --destination e2e/features/dist
```
would process files like this:

- `e2e/features/src/Login.feature` - `e2e/features/dist/Login.feature`
- `e2e/features/src/Search/Suggestions.feature` - `e2e/features/dist/Search/Suggestions.feature`
