### ISSUE TITLE
Add predefined preprocessor: scenarioNumbering

### ISSUE THREAD

**Issue by szikszail** [judit-nahaj/gherkin-precompiler#6]
Create a predefined preprocessor, which would add the index of all scenario/scenario outline to their name, to make their name unique.

It should receive a configuration:
- `{string} format` - the format how the index should be added, default: `"${i}. ${name}"`, where
    - `${i}` is the placeholder for the actual index
    - `${name}` is the placeholder for the original title of the scenario/scenario outline

**Comment by szikszail** [comment]
@judit-nahaj what do you think, would this preprocessor be useful?

**Comment by judit-nahaj** [comment]
@szikszail I think this is useful
