### ISSUE TITLE
Add predefined preprocessor: forLoop

### ISSUE THREAD

**Issue by judit-nahaj** [judit-nahaj/gherkin-precompiler#8]
Create a preprocessor for handling for loops.
A tag before the scenario should indicate that the scenario will be looped, and also the number of iterations. The iterators current value should be be included in the name of the scenario.

Example:
Feature file:

```
@loop(2)
Scenario: 3. Testing login
    Given the login page is loaded
    When "username" is entered into the username field
    And "password" is entered into the password field
    And the login button is clicked
    Then the home page should be loaded

```
What actually runs/is logged:

```
Scenario: 3. Testing login (1)
    Given the login page is loaded
    When "username" is entered into the username field
    And "password" is entered into the password field
    And the login button is clicked
    Then the home page should be loaded

Scenario: 3. Testing login (2)
    Given the login page is loaded
    When "username" is entered into the username field
    And "password" is entered into the password field
    And the login button is clicked
    Then the home page should be loaded
```

**Comment by szikszail** [comment]
@judit-nahaj please consider the following configuration options:
1. a format, how the actual iteration value should be added to the name of the scenario
1. a name of the tag which should be considered as the "loop-tag"

I would also suggest not to apply loop to backgrounds.

How would you handle the case if a scenario-outline is tagged with "loop-tag"? Would this preprocessor handle the case if we want to repease an example row?

**Comment by judit-nahaj** [comment]
1. For the format I propose something (or exactly) like the example, adding the to the end of the name. Another way I can see it work might be like " Scenario: 1."+ i +" Name", adding it after the number of the original scenario, but before the name. I prefer the first one, as it seems easier, and does not rely that much on the way scenarios are named.
2. The tag could be "@loop(i)", where "i" could be the number of iterations we need. Also, for this there should be a limit as you mentioned, to avoid scenarios running for too long, so any number between 1 and 10 should be a valid "i", in any other case the preprocessor should use a default value of 10.

I also do not see the benefit of using loop for backgrounds,

For an outline if the tag is added I think the whole outline should be repeated with all its rows, that way creating iterator*number-of-rows runs.

**Comment by judit-nahaj** [comment]
tag config, format,max config

**Comment by szikszail** [comment]
@judit-nahaj I agree with the changes.

Could you please describe what would be the format of the configuration which is passed to the precompiler?
