### ISSUE TITLE
Add predefined preprocessor: Macro

### ISSUE THREAD

**Issue by judit-nahaj** [judit-nahaj/gherkin-precompiler#9]
Create a preprocessor which handles macros. Macros should be in a format of scenario, which includes multiple steps, but is not necessarily executable on its own. So this scenario should be marked with 2 tags, one to exclude it from runs (for example an @wip tag), and the tag which defines it as a macro.
The macro tag could be @macro(${name}), where name will be the id of the macro, which therefore should be unique.

A step is also needed that can be added to the scenarios, and the macro can be activated. This should be "the macro ${name} is executed", where ${name} is the id of the created macro.
Macros should not contain macros.

Example:
```

@macro(login)
Scenario: 0. Macro for login
    Given the Login page is used
    And the username field is filled with "username"
    And the password field is filled with "password"
    And the login button is clicked

Scenario: 1. Checking the profile page
    Given macro login is executed
    And the profile page is opened
    Then the profile page should be ok

```
After preprocessing it will run as if the feature file contained:

```
Scenario: 1. Checking the profile page
    Given the Login page is used
    And the username field is filled with "username"
    And the password field is filled with "password"
    And the login button is clicked
    And the profile page is opened
    Then the profile page should be ok
```

**Comment by judit-nahaj** [comment]
step definition, tag config

**Comment by szikszail** [comment]
@judit-nahaj I agree with the specifications of the macro precompiler. I cannot wait to see it ;)
